version: '3.8'

volumes:
  web-node_modules:
  web-dot_next:
  firebase-dot_cache:

services:
  web:
    build:
      context: ./web
      target: DEVELOP
    command: ['npm', 'run', 'dev']
    volumes:
      - ./:/treco/
      - web-node_modules:/treco/web/projects/node_modules
      - web-dot_next:/treco/web/projects/.next
    environment:
      HOST: 0.0.0.0
    ports:
      - 61005:3000
      - 61015:6006
  firebase:
    build:
      context: ./firebase
    volumes:
      - ./:/treco
      - firebase-dot_cache:/root/.cache/firebase/emulators/
    command: ['--only', 'firestore,auth']
    ports:
      - 60000:60000 # Emulator Suite UI
      - 8080:8080 # firestore
      - 9099:9099 # auth
  e2e:
    build:
        context: ./e2e
    volumes:
      - ./:/treco
    working_dir: /treco/e2e/projects
    command: ["npx", "cypress", "run", "--", "--watch"]
